import type { RecommendedProduct } from '@/lib/types';

/** Static Caroma catalog slice — no embeddings, no API, no tokens. */
export interface CatalogProduct extends RecommendedProduct {
  id: string;
  tags: string[];
  rooms: Array<'bathroom' | 'kitchen' | 'laundry'>;
  scopes: Array<'shower' | 'tapware' | 'full' | 'basin' | 'toilet' | 'kitchen' | 'laundry'>;
  styles: Array<'minimalist' | 'soft' | 'any'>;
  showerTypes?: Array<'rain' | 'handheld' | 'combo'>;
}

export const CATALOG: CatalogProduct[] = [
  {
    id: 'shower-rain',
    name: 'Caroma 300mm Square Rain Shower',
    sku: '99476C',
    price: 425,
    category: 'Showers',
    collection: 'Caroma',
    description: 'A clean rain overhead for a spa-like rinse — ideal when you want a simple renovating upgrade.',
    features: ['300mm square overhead', 'Single function', 'Easy retrofit'],
    finishes: ['Chrome', 'Matte Black', 'Brushed Brass'],
    specs: { Type: 'Overhead', Size: '300mm', Warranty: '20 years (cartridge)' },
    tags: ['shower', 'rain', 'overhead', 'bathroom'],
    rooms: ['bathroom'],
    scopes: ['shower', 'full'],
    styles: ['minimalist', 'any'],
    showerTypes: ['rain'],
    accessories: [
      { name: 'Liano II Robe Hook', sku: '99802', price: 79 },
      { name: 'Liano II Soap Holder', sku: '99805', price: 95 },
    ],
    installationParts: [
      { name: 'EasySwitch® Bath/Shower Mixer In-Wall Body', sku: '99651F', price: 150, required: true },
    ],
  },
  {
    id: 'shower-handheld',
    name: 'Caroma Contura® II Hand Shower',
    sku: '308128C',
    price: 569,
    category: 'Showers',
    collection: 'Contura II',
    description: 'Multi-function hand shower on a rail — flexible for everyday rinsing and cleaning.',
    features: ['Multi-function handpiece', 'Adjustable rail', 'WELS rated'],
    finishes: ['Chrome', 'Matte Black'],
    specs: { Type: 'Hand shower on rail', Warranty: '20 years (cartridge)' },
    tags: ['shower', 'handheld', 'rail', 'bathroom'],
    rooms: ['bathroom'],
    scopes: ['shower', 'full'],
    styles: ['soft', 'any'],
    showerTypes: ['handheld'],
    accessories: [{ name: 'Contura II Soap Basket', sku: '308140', price: 89 }],
    installationParts: [
      { name: 'EasySwitch® Bath/Shower Mixer In-Wall Body', sku: '99651F', price: 150, required: true },
    ],
  },
  {
    id: 'shower-combo',
    name: 'Caroma Contura® II Rail Shower With Overhead',
    sku: '308135C',
    price: 1063,
    category: 'Showers',
    collection: 'Contura II',
    description: 'Rail + 300mm overhead with diverter — the full dual-experience shower setup.',
    features: ['Rail + overhead', 'Diverter included', 'Premium dual function'],
    finishes: ['Chrome', 'Matte Black', 'Brushed Brass'],
    specs: { Type: 'Rail + overhead', Warranty: '20 years (cartridge)' },
    tags: ['shower', 'combo', 'rail', 'overhead', 'bathroom'],
    rooms: ['bathroom'],
    scopes: ['shower', 'full'],
    styles: ['soft', 'minimalist', 'any'],
    showerTypes: ['combo'],
    accessories: [{ name: 'Contura II Towel Rail', sku: '308150', price: 149 }],
    installationParts: [
      { name: 'EasySwitch® Bath/Shower Mixer In-Wall Body', sku: '99651F', price: 150, required: true },
    ],
  },
  {
    id: 'mixer-shower',
    name: 'Liano II Bath/Shower Mixer',
    sku: '96336C',
    price: 349,
    category: 'Tapware',
    collection: 'Liano II',
    description: 'Matching bath/shower mixer with round cover plate — pairs cleanly with Liano collections.',
    features: ['WELS 6★', 'Round cover plate', 'Lead-free'],
    finishes: ['Chrome', 'Matte Black', 'Brushed Brass'],
    specs: { 'WELS Rating': '6★', Warranty: '20 years' },
    tags: ['mixer', 'tapware', 'shower', 'bathroom'],
    rooms: ['bathroom'],
    scopes: ['tapware', 'shower', 'full'],
    styles: ['minimalist', 'any'],
    installationParts: [
      { name: 'EasySwitch® Bath/Shower Mixer In-Wall Body', sku: '99651F', price: 150, required: true },
    ],
  },
  {
    id: 'basin-liano',
    name: 'Liano II Hand Wall Basin',
    sku: '853010MW',
    price: 360,
    category: 'Basins',
    collection: 'Liano II',
    description: 'Fine fire clay wall basin with a thin rim — a modern staple for full bathroom specs.',
    features: ['Fine fire clay', 'Thin rim', 'Matte white'],
    finishes: ['Matte White'],
    specs: { Material: 'Fine fire clay', Colour: 'Matte white', Warranty: '10 years' },
    tags: ['basin', 'bathroom', 'wall'],
    rooms: ['bathroom'],
    scopes: ['full', 'basin'],
    styles: ['minimalist', 'any'],
    accessories: [{ name: 'Liano II Basin Dress Ring', sku: '96340', price: 65 }],
    installationParts: [
      { name: 'Universal Bottle Trap', sku: '303250', price: 89, required: true },
    ],
  },
  {
    id: 'mixer-basin',
    name: 'Liano II Wall Basin/Bath Mixer',
    sku: '96325C',
    price: 329,
    category: 'Tapware',
    collection: 'Liano II',
    description: 'Wall-mounted basin mixer — lead-free with a low 4.5 L/min flow.',
    features: ['WELS 6★', '4.5 L/min', 'Lead-free'],
    finishes: ['Chrome', 'Matte Black', 'Brushed Brass'],
    specs: { 'Flow Rate': '4.5 L/min', 'WELS Rating': '6★', Warranty: '20 years' },
    tags: ['mixer', 'basin', 'tapware', 'bathroom'],
    rooms: ['bathroom'],
    scopes: ['tapware', 'full', 'basin'],
    styles: ['minimalist', 'any'],
    installationParts: [
      { name: 'EasySwitch® Basin/Bath Mixer In-Wall Body', sku: '99635F', price: 150, required: true },
    ],
  },
  {
    id: 'toilet-liano',
    name: 'Liano Cleanflush® WF Invisi Suite',
    sku: '766100W',
    price: 690,
    category: 'Toilet Suites',
    collection: 'Liano',
    description: 'Rimless Cleanflush® suite with GermGard® — the full-bathroom sanitation anchor.',
    features: ['Rimless Cleanflush®', 'GermGard®', 'In-wall cistern ready'],
    finishes: ['Gloss White'],
    specs: { Type: 'Invisi suite', Finish: 'Gloss white', Warranty: '10 years' },
    tags: ['toilet', 'suite', 'bathroom'],
    rooms: ['bathroom'],
    scopes: ['full', 'toilet'],
    styles: ['minimalist', 'soft', 'any'],
    installationParts: [
      { name: 'Invisi Series II® Round Flush Plate', sku: '237010', price: 130, required: true },
    ],
  },
  {
    id: 'kitchen-mixer',
    name: 'Caroma Liano II Sink Mixer',
    sku: '96370C',
    price: 399,
    category: 'Kitchen Tapware',
    collection: 'Liano II',
    description: 'Gooseneck sink mixer for kitchen benches — kitchen-scoped so bathroom SKUs stay out.',
    features: ['Gooseneck spout', 'WELS rated', 'Lead-free'],
    finishes: ['Chrome', 'Matte Black'],
    specs: { Room: 'Kitchen', Warranty: '20 years' },
    tags: ['kitchen', 'mixer', 'sink'],
    rooms: ['kitchen'],
    scopes: ['kitchen'],
    styles: ['minimalist', 'any'],
    accessories: [{ name: 'Sink Basket Waste', sku: '301185', price: 55 }],
    installationParts: [{ name: 'Flexible Connectors (pair)', sku: 'FC-PAIR', price: 35, required: true }],
  },
  {
    id: 'kitchen-sink',
    name: 'Caroma Studio Double Bowl Sink',
    sku: '852400',
    price: 780,
    category: 'Kitchen Sinks',
    collection: 'Studio',
    description: 'Durable double-bowl kitchen sink for prep and cleanup side-by-side.',
    features: ['Double bowl', 'Stainless steel', 'Drainer option'],
    finishes: ['Stainless Steel'],
    specs: { Material: 'Stainless steel', Bowls: '2', Warranty: '25 years' },
    tags: ['kitchen', 'sink'],
    rooms: ['kitchen'],
    scopes: ['kitchen'],
    styles: ['any'],
    accessories: [{ name: 'Sink Basket Waste', sku: '301185', price: 55 }],
  },
  {
    id: 'laundry-tub',
    name: 'Caroma Laundry Tub Cabinet 45L',
    sku: '301700',
    price: 549,
    category: 'Laundry',
    collection: 'Caroma',
    description: 'Compact laundry tub with cabinet storage — sized for typical laundry niches.',
    features: ['45L capacity', 'Cabinet storage', 'Bypass plumbing friendly'],
    finishes: ['White'],
    specs: { Capacity: '45L', Room: 'Laundry', Warranty: '10 years' },
    tags: ['laundry', 'tub'],
    rooms: ['laundry'],
    scopes: ['laundry'],
    styles: ['any'],
    installationParts: [{ name: 'Laundry Bypass Kit', sku: 'LBK-1', price: 45, required: true }],
  },
];

export function toRecommended(p: CatalogProduct): RecommendedProduct {
  const { id: _id, tags: _tags, rooms: _rooms, scopes: _scopes, styles: _styles, showerTypes: _st, ...rest } = p;
  return rest;
}
