import { Product } from './types';

// A curated (illustrative) Abercrombie & Fitch–style catalog.
// Prices in USD. Not affiliated with A&F — demo data only.
export const CATALOG: Product[] = [
  {
    id: 'anf-tee-essential',
    name: 'Essential Crewneck Tee',
    price: 30,
    category: 'Tops',
    dept: 'Unisex',
    occasions: ['everyday', 'going-out'],
    palette: 'neutral',
    colors: [
      { name: 'White', hex: '#F3F1EC' },
      { name: 'Black', hex: '#1B1B1A' },
      { name: 'Heather Grey', hex: '#B9B6AF' },
    ],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    blurb: 'A weighty cotton crew with a clean neckline — the layering block every edit is built on.',
  },
  {
    id: 'anf-hoodie-signature',
    name: 'Signature Fleece Hoodie',
    price: 70,
    category: 'Tops',
    dept: 'Unisex',
    occasions: ['everyday', 'cold-weather', 'active'],
    palette: 'earthy',
    colors: [
      { name: 'Oatmeal', hex: '#DAD0BE' },
      { name: 'Forest', hex: '#38463A' },
      { name: 'Navy', hex: '#20304A' },
    ],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    blurb: 'Brushed-back heavyweight fleece with a relaxed hood — cozy without the bulk.',
  },
  {
    id: 'anf-jean-90s',
    name: "90s Relaxed Jean",
    price: 90,
    category: 'Bottoms',
    dept: 'Unisex',
    occasions: ['everyday', 'going-out'],
    palette: 'neutral',
    colors: [
      { name: 'Medium Wash', hex: '#6C86A6' },
      { name: 'Ecru', hex: '#E7DFCD' },
      { name: 'Washed Black', hex: '#2C2C2E' },
    ],
    sizes: ['28', '30', '32', '34', '36'],
    blurb: 'A vintage-inspired straight leg that sits high and breaks clean at the ankle.',
  },
  {
    id: 'anf-jean-athletic',
    name: 'Athletic Skinny Jean',
    price: 80,
    category: 'Bottoms',
    dept: 'Mens',
    occasions: ['everyday', 'going-out'],
    palette: 'neutral',
    colors: [
      { name: 'Dark Wash', hex: '#3C4A5E' },
      { name: 'Jet Black', hex: '#232326' },
    ],
    sizes: ['28', '30', '32', '34', '36'],
    blurb: 'Room through the thigh, tapered below — built with performance stretch denim.',
  },
  {
    id: 'anf-shirt-camp',
    name: 'Linen-Blend Camp Shirt',
    price: 70,
    category: 'Tops',
    dept: 'Unisex',
    occasions: ['going-out', 'everyday'],
    palette: 'earthy',
    colors: [
      { name: 'Sand', hex: '#D8C6A6' },
      { name: 'Olive', hex: '#6E6B45' },
      { name: 'White', hex: '#F3F1EC' },
    ],
    sizes: ['S', 'M', 'L', 'XL'],
    blurb: 'Breathable linen blend with an open camp collar — effortless for warm-weather evenings.',
  },
  {
    id: 'anf-jacket-vegan-leather',
    name: 'Vegan Leather Moto Jacket',
    price: 150,
    category: 'Outerwear',
    dept: 'Womens',
    occasions: ['going-out', 'cold-weather'],
    palette: 'bold',
    colors: [
      { name: 'Black', hex: '#1B1B1A' },
      { name: 'Cognac', hex: '#8A5A34' },
    ],
    sizes: ['XS', 'S', 'M', 'L'],
    blurb: 'A sleek moto with asymmetric zip and polished hardware — instant edge over any look.',
  },
  {
    id: 'anf-jacket-quilted',
    name: 'Quilted Liner Jacket',
    price: 120,
    category: 'Outerwear',
    dept: 'Unisex',
    occasions: ['cold-weather', 'everyday'],
    palette: 'earthy',
    colors: [
      { name: 'Khaki', hex: '#B9A681' },
      { name: 'Black', hex: '#1B1B1A' },
      { name: 'Olive', hex: '#5E623F' },
    ],
    sizes: ['S', 'M', 'L', 'XL'],
    blurb: 'Diamond-quilted with a lightweight fill — the perfect mid layer or standalone shell.',
  },
  {
    id: 'anf-dress-wrap',
    name: 'Wrap Midi Dress',
    price: 110,
    category: 'Dresses',
    dept: 'Womens',
    occasions: ['going-out', 'workwear'],
    palette: 'bold',
    colors: [
      { name: 'Merlot', hex: '#5E2231' },
      { name: 'Black', hex: '#1B1B1A' },
      { name: 'Emerald', hex: '#1F4A3C' },
    ],
    sizes: ['XS', 'S', 'M', 'L'],
    blurb: 'A true wrap silhouette that cinches the waist and flows to a flattering midi length.',
  },
  {
    id: 'anf-bodysuit-ribbed',
    name: 'Ribbed Scoop Bodysuit',
    price: 40,
    category: 'Tops',
    dept: 'Womens',
    occasions: ['going-out', 'everyday'],
    palette: 'neutral',
    colors: [
      { name: 'Black', hex: '#1B1B1A' },
      { name: 'Bone', hex: '#E9E2D4' },
      { name: 'Slate', hex: '#4C5560' },
    ],
    sizes: ['XS', 'S', 'M', 'L'],
    blurb: 'A second-skin rib with a clean scoop — tucks perfectly into denim or tailored pants.',
  },
  {
    id: 'anf-sweatpant-fleece',
    name: 'Fleece Sweatpant',
    price: 60,
    category: 'Bottoms',
    dept: 'Unisex',
    occasions: ['everyday', 'active', 'cold-weather'],
    palette: 'neutral',
    colors: [
      { name: 'Heather Grey', hex: '#B9B6AF' },
      { name: 'Black', hex: '#1B1B1A' },
      { name: 'Navy', hex: '#20304A' },
    ],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    blurb: 'Tapered fleece jogger with a soft brushed interior — lounge-ready, street-approved.',
  },
  {
    id: 'anf-shirt-oxford',
    name: 'Classic Oxford Button-Up',
    price: 80,
    category: 'Tops',
    dept: 'Mens',
    occasions: ['workwear', 'going-out', 'everyday'],
    palette: 'neutral',
    colors: [
      { name: 'White', hex: '#F3F1EC' },
      { name: 'Blue Stripe', hex: '#9FB6CE' },
      { name: 'Light Blue', hex: '#BFD1E3' },
    ],
    sizes: ['S', 'M', 'L', 'XL'],
    blurb: 'Crisp cotton oxford with a structured collar — dress it up or roll the sleeves.',
  },
  {
    id: 'anf-sweater-cashmere',
    name: 'Cashmere-Blend Sweater',
    price: 110,
    category: 'Tops',
    dept: 'Unisex',
    occasions: ['cold-weather', 'workwear', 'going-out'],
    palette: 'earthy',
    colors: [
      { name: 'Camel', hex: '#B08A5A' },
      { name: 'Charcoal', hex: '#3A3A3C' },
      { name: 'Cream', hex: '#E8DFCD' },
    ],
    sizes: ['S', 'M', 'L', 'XL'],
    blurb: 'A luxe cashmere blend with a ribbed crew — warmth that feels weightless.',
  },
  {
    id: 'anf-pant-cargo',
    name: 'Utility Cargo Pant',
    price: 80,
    category: 'Bottoms',
    dept: 'Unisex',
    occasions: ['everyday', 'active'],
    palette: 'earthy',
    colors: [
      { name: 'Olive', hex: '#5E623F' },
      { name: 'Stone', hex: '#C4B79B' },
      { name: 'Black', hex: '#1B1B1A' },
    ],
    sizes: ['28', '30', '32', '34', '36'],
    blurb: 'Relaxed cargo with anchored pockets — the utility staple that grounds a look.',
  },
  {
    id: 'anf-jacket-denim',
    name: 'Vintage Denim Jacket',
    price: 110,
    category: 'Outerwear',
    dept: 'Unisex',
    occasions: ['everyday', 'going-out'],
    palette: 'neutral',
    colors: [
      { name: 'Medium Wash', hex: '#6C86A6' },
      { name: 'Ecru', hex: '#E7DFCD' },
    ],
    sizes: ['S', 'M', 'L', 'XL'],
    blurb: 'A slightly oversized trucker with worn-in indigo — layers over everything.',
  },
  {
    id: 'anf-vest-puffer',
    name: 'Down Puffer Vest',
    price: 100,
    category: 'Outerwear',
    dept: 'Unisex',
    occasions: ['cold-weather', 'active', 'everyday'],
    palette: 'bold',
    colors: [
      { name: 'Burnt Orange', hex: '#B4652C' },
      { name: 'Black', hex: '#1B1B1A' },
      { name: 'Forest', hex: '#38463A' },
    ],
    sizes: ['S', 'M', 'L', 'XL'],
    blurb: 'Packable down fill with a high collar — core warmth without losing mobility.',
  },
  {
    id: 'anf-skirt-slip',
    name: 'Satin Slip Skirt',
    price: 70,
    category: 'Bottoms',
    dept: 'Womens',
    occasions: ['going-out', 'workwear'],
    palette: 'bold',
    colors: [
      { name: 'Champagne', hex: '#D9C6A0' },
      { name: 'Black', hex: '#1B1B1A' },
      { name: 'Sapphire', hex: '#24406E' },
    ],
    sizes: ['XS', 'S', 'M', 'L'],
    blurb: 'A bias-cut satin midi with fluid drape — pairs high with a tucked knit or tee.',
  },
];
