/**
 * Apply the grounded domain-keyword/synonym sets generated by
 * generate-placemakers-domain-keywords.ts onto the real PlaceMakers data, and
 * wire them into actual retrieval.
 *
 * Three additive things happen here, all scoped to projectId: 'placemakers',
 * none of them touching an existing field:
 *
 *  1. `metadata.domainKeywords` is $set on `products` (nested under a new
 *     `metadata` object — products had no such object before) and on the
 *     matching `documents` (chunkIndex:0, the narrative doc), joined by
 *     subClassCode -> category-level domainKeywords, PLUS any cross-cutting
 *     glossary term whose `appliesToCategoryKeywords` matches the product's
 *     category text. `metadata.keywords` (the literal source keywords) is
 *     never touched.
 *
 *  2. Retrieval wiring: `$vectorSearch` in product.service.ts is PURE
 *     embedding search against the `embedding` field of the `documents`
 *     collection — it cannot "read" an un-embedded metadata field, and the
 *     known Atlas trap (see project memory: "Atlas vector filter paths") means
 *     adding a new filter path is not safe without an index change we are not
 *     making here. So instead of touching (or re-embedding) the EXISTING
 *     narrative document, we add a brand-new, SEPARATE document per product
 *     (chunkIndex: 1, its own sourceUrl) whose embedded text explicitly
 *     contains the product name plus its domain-keyword synonyms. It carries
 *     the same metadata.sku/url/price/category/etc. as the narrative doc so
 *     it renders like a normal product hit if it surfaces. Because this is a
 *     NEW document (not a mutation of the old one) it needs no reindexing —
 *     the existing Atlas vector index already covers every document in the
 *     collection via the `embedding` field.
 *
 *  3. This is why the fix is real for TODAY's data, not just future
 *     re-embeds: the synonym document is embedded and written right now, in
 *     this script, so semantic search over "casement window hardware" etc.
 *     can match it immediately.
 *
 * Resumable: products already carrying `metadata.domainKeywordsAt` are
 * skipped for the products/documents metadata step unless --force; synonym
 * documents already written (by sourceUrl) are skipped via upsert (cheap to
 * re-run, but we track a marker to avoid re-embedding for cost).
 *
 * Usage:
 *   npx tsx src/scripts/apply-placemakers-domain-keywords.ts [--force] [--limit N] [--only-category SUBCLASSCODE] [--skip-synonym-docs] [--dry]
 */
import path from 'path';
import { config as dotenv } from 'dotenv';
dotenv({ path: path.resolve(__dirname, '../../../../.env') });

import { MongoClient } from 'mongodb';
import { embedTexts } from '../services/knowledge/embedder';

const PROJECT_ID = 'placemakers';
const FORCE = process.argv.includes('--force');
const DRY = process.argv.includes('--dry');
const SKIP_SYNONYM_DOCS = process.argv.includes('--skip-synonym-docs');
const limitArg = process.argv.find((a) => a.startsWith('--limit'));
const LIMIT = limitArg ? parseInt(process.argv[process.argv.indexOf(limitArg) + 1] || limitArg.split('=')[1] || '0', 10) : 0;
const onlyCatArg = process.argv.find((a) => a.startsWith('--only-category'));
const ONLY_CATEGORY = onlyCatArg ? (process.argv[process.argv.indexOf(onlyCatArg) + 1] || onlyCatArg.split('=')[1]) : undefined;

function categoryText(p: any): string {
  return [p.category, p.subClassName, ...(p.categoryPath || [])].filter(Boolean).join(' ').toLowerCase();
}

function escapeRegex(s: string): string {
  return s.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
}

/**
 * Word-boundary keyword match — NOT a raw substring test. A raw `.includes()`
 * lets a keyword like "gib" match inside an unrelated word, and (more
 * importantly, see genericity below) never distinguishes "this keyword
 * appears" from "this keyword appears as its own trade term".
 */
function hasKeyword(text: string, keyword: string): boolean {
  const re = new RegExp(`\\b${escapeRegex(keyword)}\\b`, 'i');
  return re.test(text);
}

async function main() {
  const uri = process.env.MONGODB_URI;
  if (!uri) throw new Error('MONGODB_URI not set');
  const client = new MongoClient(uri);
  await client.connect();
  const db = client.db('journeyx');
  const P = db.collection('products');
  const D = db.collection('documents');
  const K = db.collection('placemakers_domain_keywords');
  const G = db.collection('placemakers_domain_glossary');

  console.log('loading category domain-keyword map…');
  const kwRows = await K.find({ projectId: PROJECT_ID }).toArray();
  const kwBySubClass = new Map<string, string[]>(kwRows.map((r: any) => [r.subClassCode, r.domainKeywords || []]));
  console.log(`  ${kwBySubClass.size} categories with generated keywords`);

  const glossaryDoc = await G.findOne({ projectId: PROJECT_ID });
  const glossaryTerms: any[] = glossaryDoc?.terms || [];
  console.log(`  ${glossaryTerms.length} cross-cutting glossary terms loaded`);

  // ── Genericity of glossary appliesToCategoryKeywords ──────────────────
  // Root cause of the dilution regression: a keyword like "hardware" or
  // "fastener" in a glossary entry's appliesToCategoryKeywords appears in a
  // huge fraction of ALL category text (this is a hardware/building-supplies
  // catalogue — "hardware" is everywhere), so the old `ct.includes(k)` check
  // let cross-cutting glossary terms (roofing nails, ramset, joist hangers…)
  // attach to products they have nothing to do with, just because the
  // product's category path happens to contain one generic word in common.
  // Fix: measure, per keyword, what fraction of the REAL 1362 categories it
  // appears in. A keyword that shows up in >12% of categories is "generic"
  // and cannot by itself justify attaching a glossary entry — either a
  // SPECIFIC (non-generic) keyword must match, or at least two keywords
  // (generic or not) must co-occur, which is a much stronger signal that the
  // category is actually topically related rather than sharing one common word.
  const catRowsForFreq = kwRows as any[];
  const catTextsForFreq = catRowsForFreq.map((r) => categoryText(r));
  const allApplyKeywords = new Set<string>();
  for (const g of glossaryTerms) for (const k of (g.appliesToCategoryKeywords || [])) allApplyKeywords.add(String(k).trim().toLowerCase());
  const keywordFreq = new Map<string, number>();
  for (const k of allApplyKeywords) {
    let n = 0;
    for (const ct of catTextsForFreq) if (hasKeyword(ct, k)) n++;
    keywordFreq.set(k, n);
  }
  const GENERIC_THRESHOLD = 0.12 * catTextsForFreq.length;
  const genericKeywords = new Set([...keywordFreq.entries()].filter(([, n]) => n > GENERIC_THRESHOLD).map(([k]) => k));
  console.log(`  ${genericKeywords.size}/${allApplyKeywords.size} applies-keywords are generic (>${Math.round(GENERIC_THRESHOLD)} of ${catTextsForFreq.length} categories) and cannot solo-trigger a glossary attach: ${[...genericKeywords].slice(0, 15).join(', ')}${genericKeywords.size > 15 ? '…' : ''}`);

  const filter: any = { projectId: PROJECT_ID, subClassCode: { $in: [...kwBySubClass.keys()] } };
  if (ONLY_CATEGORY) filter.subClassCode = ONLY_CATEGORY;
  if (!FORCE) filter.domainKeywordsAt = { $exists: false };

  const products = await P.find(filter, {
    projection: {
      parentSku: 1, name: 1, description: 1, category: 1, categoryPath: 1, subClassName: 1, subClassCode: 1,
      priceUSD: 1, images: 1, colors: 1, sizes: 1, url: 1, stock: 1, web: 1, variantCount: 1,
    },
  }).limit(LIMIT || 0).toArray();
  console.log(`products to process: ${products.length}`);

  let metaUpdated = 0, docMetaUpdated = 0, synonymDocsWritten = 0, skippedNoKeywords = 0;
  const BATCH = 200;

  for (let i = 0; i < products.length; i += BATCH) {
    const batch = products.slice(i, i + BATCH);

    const prodOps: any[] = [];
    const docMetaOps: any[] = [];
    const synonymCandidates: { p: any; domainKeywords: string[]; text: string; url: string }[] = [];

    for (const p of batch as any[]) {
      // Category-specific keywords (from the per-subClassCode LLM pass) are
      // the LEGITIMATE part of this system — they solved the original
      // "casement" / "hinged window" problem and are grounded in real sample
      // products for exactly this category. Weight them first/primary.
      const catKw = [...new Set((kwBySubClass.get(p.subClassCode) || []).map((s) => String(s).trim().toLowerCase()).filter(Boolean))];
      const ct = categoryText(p);

      // Cross-cutting glossary: tightened match. A glossary entry attaches
      // only if it has a SPECIFIC (non-generic) keyword hit, or 2+ keyword
      // hits total (co-occurrence) — see genericity computation above. Each
      // attached entry is scored by how specific its matched keywords are, so
      // only the most genuinely-relevant few survive the cap below.
      const scoredGlossaryHits: { terms: string[]; score: number }[] = [];
      for (const g of glossaryTerms) {
        const applies: string[] = (g.appliesToCategoryKeywords || []).map((k: string) => String(k).trim().toLowerCase());
        const matched = applies.filter((k) => hasKeyword(ct, k));
        if (!matched.length) continue;
        const specificMatches = matched.filter((k) => !genericKeywords.has(k));
        if (specificMatches.length < 1 && matched.length < 2) continue; // lone generic hit — not enough signal
        const score = matched.reduce((s, k) => s + 1 / Math.max(1, keywordFreq.get(k) || 1), 0);
        scoredGlossaryHits.push({ terms: [g.term, ...(g.synonyms || [])], score });
      }
      scoredGlossaryHits.sort((a, b) => b.score - a.score);
      const GLOSSARY_CAP = 5; // a handful, not ~40 — glossary is secondary to the grounded category keywords
      const glossaryHits = scoredGlossaryHits.slice(0, GLOSSARY_CAP).flatMap((h) => h.terms);

      const domainKeywords = [...new Set([...catKw, ...glossaryHits].map((s) => String(s).trim().toLowerCase()).filter(Boolean))];
      if (!domainKeywords.length) { skippedNoKeywords++; continue; }

      prodOps.push({ updateOne: {
        filter: { _id: p._id },
        update: { $set: {
          'metadata.domainKeywords': domainKeywords,
          'metadata.categoryDomainKeywords': catKw,
          'metadata.glossaryDomainKeywords': [...new Set(glossaryHits.map((s) => String(s).trim().toLowerCase()))],
          domainKeywordsAt: new Date(),
        } },
      } });

      const url = p.web?.productUrl || p.url || `product://${PROJECT_ID}/${p.parentSku}`;
      // Match by metadata.sku, NOT sourceUrl: documents written before the URL
      // backfill still carry the old synthetic `product://…` sourceUrl (the
      // backfill only patched metadata.url, deliberately never touching
      // sourceUrl — see patch-placemakers-doc-metadata.ts). Matching on the
      // real product url here would silently miss most of the catalogue, which
      // is exactly what happened on the first pass (only 1,851/40,793 matched)
      // — metadata.sku is the join key already proven safe for this exact
      // problem.
      docMetaOps.push({ updateOne: {
        filter: { projectId: PROJECT_ID, 'metadata.sku': p.parentSku, chunkIndex: 0 },
        update: { $set: { 'metadata.domainKeywords': domainKeywords } },
      } });

      if (!SKIP_SYNONYM_DOCS) {
        // Weighting, most to least important:
        //   1. product name — repeated, so it dominates the embedding
        //   2. category / sub-category — the real classification
        //   3. category-specific domain keywords (grounded, up to 15) — the
        //      part that actually solved the original problem
        //   4. cross-cutting glossary terms (capped to 5, explicitly labelled
        //      as general trade terms so they read as secondary, not mixed in
        //      indiscriminately with the specific ones)
        const catKwCapped = catKw.slice(0, 15);
        const glossaryCapped = [...new Set(glossaryHits.map((s) => String(s).trim().toLowerCase()))].slice(0, GLOSSARY_CAP * 3); // terms+synonyms per entry
        const text = [
          `${p.name}. ${p.name}.`,
          p.category ? `Category: ${p.category}.` : '',
          p.subClassName ? `Sub-category: ${p.subClassName}.` : '',
          catKwCapped.length ? `Also searched as: ${catKwCapped.join(', ')}.` : '',
          glossaryCapped.length ? `Related general trade terms: ${glossaryCapped.join(', ')}.` : '',
        ].filter(Boolean).join(' ');
        synonymCandidates.push({ p, domainKeywords, text, url });
      }
    }

    if (!DRY && prodOps.length) { await P.bulkWrite(prodOps, { ordered: false }); metaUpdated += prodOps.length; }
    else if (DRY) metaUpdated += prodOps.length;

    if (!DRY && docMetaOps.length) { await D.bulkWrite(docMetaOps, { ordered: false }); docMetaUpdated += docMetaOps.length; }
    else if (DRY) docMetaUpdated += docMetaOps.length;

    if (!DRY && synonymCandidates.length) {
      const embeddings = await embedTexts(synonymCandidates.map((c) => c.text));
      const now = new Date();
      const synOps = synonymCandidates.map((c, j) => {
        const p = c.p;
        return { updateOne: {
          filter: { projectId: PROJECT_ID, sourceUrl: `${c.url}#synonyms`, chunkIndex: 1 },
          update: { $set: {
            projectId: PROJECT_ID, brand: PROJECT_ID, sourceUrl: `${c.url}#synonyms`,
            title: p.name, content: c.text, chunk: c.text, chunkIndex: 1,
            metadata: {
              type: 'product', brand: PROJECT_ID, url: c.url, sku: p.parentSku,
              synonymDoc: true, domainKeywords: c.domainKeywords,
              ...(p.priceUSD ? { price: p.priceUSD.min, currency: 'USD' } : {}),
              ...(p.category ? { category: p.category } : {}),
              ...(p.categoryPath?.length ? { categoryPath: p.categoryPath } : {}),
              ...(p.stock ? { stock: p.stock } : {}),
              ...(p.images?.length ? { images: p.images.slice(0, 6) } : {}),
              variantCount: p.variantCount,
            },
            embedding: embeddings[j], crawledAt: now, updatedAt: now,
          } }, upsert: true } };
      });
      await D.bulkWrite(synOps, { ordered: false });
      synonymDocsWritten += synOps.length;
    } else if (DRY) synonymDocsWritten += synonymCandidates.length;

    console.log(`  ${Math.min(i + BATCH, products.length)}/${products.length} · metaUpdated=${metaUpdated} docMeta=${docMetaUpdated} synonymDocs=${synonymDocsWritten} skippedNoKw=${skippedNoKeywords}`);
  }

  console.log(JSON.stringify({ processed: products.length, metaUpdated, docMetaUpdated, synonymDocsWritten, skippedNoKeywords, dry: DRY }, null, 2));
  await client.close();
}

main().catch((e) => { console.error(e); process.exit(1); });
